### ISSUE TITLE
[question] using proxywrap to send test requests?

### ISSUE THREAD

**Issue by kurttheviking** [daguej/node-proxywrap#5]
Thank you so much for putting this together. We've found it tremendously useful.

I was curious if you had any thoughts about using the same wrapper (or some implementation of it) to mock outbound proxy requests? For instance, I'd like to test locally that data is being received correctly by small api service so it'd be great to wrap a [request](https://github.com/mikeal/request) with the protocol specs...even if the IP address and so forth are null or programmatically set. 

Before hacking away at something I thought I would check with you because I imagine you had some tooling to test this...even if not necessarily released.

**Comment by daguej** [comment]
For testing, I whipped up a simple TCP proxy server that sends PROXY headers and then just pipes data.

```
var net = require('net');


net.createServer(function(socket) {

    var s = net.connect(8086, '127.0.0.1', function() {

        s.write('PROXY TCP4 127.0.13.37 127.0.0.1 1337 8089\r\n');
        socket.pipe(s);
        s.pipe(socket);


        s.on('error', function() {});
        socket.on('error', function() {});

        s.on('close', function() {
            socket.destroy();
        });

        socket.on('close', function() {
            s.destroy();
        });
    });

}).listen(8089);
```

In this example, the client (ie browser) connects to 8089, and this connects to the real server on 8086.

Obviously, this is very Q&D, but it worked for me.  I'm open to suggestions for something a little more integrated.

**Comment by kurttheviking** [comment]
thanks! this works well enough for our purposes; I appreciate the quick response
